language: php

git:
  depth: 2

php:
- 7.0
- 7.1
- 7.2
- nightly

env:
- USE_SYMFONY_POLYFILL_INTL_NORMALIZER=true
- USE_PATCHWORK_UTF8_NORMALIZER=true

matrix:
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.1
      env: LINT=true
    - php: 7.2
    - php: nightly
      env: NIGHTLY=true
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.php-cs-fixer

install:
- phpenv config-rm xdebug.ini || true
- travis_retry composer self-update
- if [[ $NIGHTLY = true ]]; then
    composer remove --dev friendsofphp/php-cs-fixer;
    composer validate;
  fi
- travis_retry composer install --no-interaction
- if [[ $USE_SYMFONY_POLYFILL_INTL_NORMALIZER = true ]]; then
    phpenv config-rm intl.ini || true;
    composer require symfony/polyfill-intl-normalizer;
    composer validate;
  fi
- if [[ $USE_PATCHWORK_UTF8_NORMALIZER = true ]]; then
    phpenv config-rm intl.ini || true;
    composer require patchwork/utf8;
    composer validate;
  fi
- travis_retry composer dump-autoload --optimize

script:
- if [[ $LINT = true ]]; then
    composer validate;
    composer unicode-normalization-stream-filter:cs-lint;
  fi
- if [[ $(( $TRAVIS_BUILD_NUMBER % 10 )) = 0 ]]; then
    composer unicode-normalization-stream-filter:test-all;
  else
    composer unicode-normalization-stream-filter:test;
  fi

sudo: false

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    on_success: always
    on_failure: always
    secure: EIArU4j71+9CBEwVsvwuqeKYG3JrVtCOy5msAgmMoV+WCe+xnpb1N78tNv9UIzT4EJgpFzam1y37sGsyCG8krN0X2fDfoLp6NT7MKx5S8x+3iv/TckCyrzCiltb55dLBkjc+b7RWcy6pBz+g8UP2qvl+Q9uVKSg2z/E+Rl9/udpgHA9r6KA6yMen+tT/0ik7/rhCXrGxg+Lhx6przg//dmWdNb5oMTJnWQ+uOkK6YYTTeonFLhLV7xM/TM1X/U6zhHk4w6xU+pa0d/pOIgwYD6kVRB55IV0jHCdiwHIEEuzdFPQ3vDMu7c3C+eXvlrq9qRSNKpaOu2AoToe9cFZSonoks5Ti8jDOJZmBzl0ydDIJclJdWz8t7cYlh7Cxmm0VBFVBTk+cC0SK2mR6AicvTOUwb41ZhR8Wl40OuKtzQZIAl2LlMD6JVipkJ/z8jqI5kLfg3rflnvoUKmig7/MC4FI3Vuq9SUl4oWMviLCikSyG9GnutG/A2gamJ4qzS62UZtKVPHDZ+26sGNHz+4/ALoWpZtJVT3/E5B7ekk8eC2KKLk6L0jSIgpUYlDBkhhthYMu8Sor8DesN46HlaID70vJxWaPbDwNPymFe38qES2kZBFlnZbxlppOV9FLEImGRUxuo/1Gpg/6zESzTYGN28BXiWrO4NUbHKxrjuSk0Z8I=
